#服务器端口
server:
  port: 8015
  servlet:
    #拦截路径
    context-path: /

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.energy.dev.url}
    username: ${blade.datasource.energy.dev.username}
    password: ${blade.datasource.energy.dev.password}
#
push:
  base:
    url: ${push.base.url}

